// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iohbhhccybmmbahvjigk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvaGJoaGNjeWJtbWJhaHZqaWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzE5MTEsImV4cCI6MjA2Njk0NzkxMX0.h4wt7iuGUvedznmo0GWWzIRnMw9V9o0T24VRY1WeFwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});